### ISSUE TITLE
recipes are not idempotent

### ISSUE THREAD

**Issue by jkerry** [dhoer/chef-selenium#28] opened 2016-08-21 12:22 UTC
We'd like to wrap these recipes in an internal cookbook and set chef for continuous runs but the recipes have resources, such as the selenium install ps1 script that converge every time.  It'd be cool if these resources could be wrapped in intelligent guards to prevent needless execution.

**Comment by dhoer** [comment] 2016-08-22 05:03
It has been a while since I wrote these scripts and I'm not sure what you mean by ps1 script.  Can you submit a PR?

**Comment by jkerry** [comment] 2016-08-22 11:58
Certainly. Just wanted to get an issue in first. Ps1 -> powershell script file extension.

**Comment by dhoer** [comment] 2016-08-25 21:59
I think part of the problem is because I'm using converge_by incorrectly.  Maybe removing those unneeded calls will fix the issue.

**Comment by dhoer** [comment] 2017-02-05 03:22
See if the  new 4.0.0 release fixes this.

**Comment by jkerry** [comment] 2017-02-06 19:58
Awesome!  I'll take a look soon when we reprovision our grid infrastructure

**Comment by dhoer** [comment] 2017-08-27 17:04
@jkerry can I close this issue?

**Comment by jkerry** [comment] 2017-08-27 17:25
Yep, thanks!

**Closed as completed** 2017-08-27 17:30 UTC
